package dto;
// Generated Apr 9, 2019 7:50:29 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietCauhinhLopId generated by hbm2java
 */
@Embeddable
public class ChitietCauhinhLopId implements java.io.Serializable {

    private int idLop = -1;
    private int idNamHoc = -1;
    private int idCauHinh = -1;

    public ChitietCauhinhLopId() {
    }

    public ChitietCauhinhLopId(int idLop, int idNamHoc, int idCauHinh) {
        this.idLop = idLop;
        this.idNamHoc = idNamHoc;
        this.idCauHinh = idCauHinh;
    }

    @Column(name = "idLop", nullable = false)
    public int getIdLop() {
        return this.idLop;
    }

    public void setIdLop(int idLop) {
        this.idLop = idLop;
    }

    @Column(name = "idNamHoc", nullable = false)
    public int getIdNamHoc() {
        return this.idNamHoc;
    }

    public void setIdNamHoc(int idNamHoc) {
        this.idNamHoc = idNamHoc;
    }

    @Column(name = "idCauHinh", nullable = false)
    public int getIdCauHinh() {
        return this.idCauHinh;
    }

    public void setIdCauHinh(int idCauHinh) {
        this.idCauHinh = idCauHinh;
    }

    public boolean equals(ChitietCauhinhLopId other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ChitietCauhinhLopId)) {
            return false;
        }
        ChitietCauhinhLopId castOther = (ChitietCauhinhLopId) other;

        return (this.getIdLop() == castOther.getIdLop())
                && (this.getIdNamHoc() == castOther.getIdNamHoc())
                && (this.getIdCauHinh() == castOther.getIdCauHinh());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdLop();
        result = 37 * result + this.getIdNamHoc();
        result = 37 * result + this.getIdCauHinh();
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ChitietCauhinhLopId other = (ChitietCauhinhLopId) obj;
        if (this.idLop != other.idLop) {
            return false;
        }
        if (this.idNamHoc != other.idNamHoc) {
            return false;
        }
        if (this.idCauHinh != other.idCauHinh) {
            return false;
        }
        return true;
    }

}
