package dto;
// Generated Apr 15, 2019 3:40:32 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Diem generated by hbm2java
 */
@Entity
@Table(name = "diem", catalog = "quanlyhocsinh", uniqueConstraints = @UniqueConstraint(columnNames = {"idHocSinh", "idNamHoc", "idHocKy", "idMonHoc"})
)
public class Diem implements java.io.Serializable {

    private Integer idDiem;
    private Hocky hocky;
    private HocsinhLophoc hocsinhLophoc;
    private Monhoc monhoc;
    private Double diem15Phut;
    private Double diem1Tiet;
    private Double diemCuoiKy;
    private Set<ChitietCauhinhDiem> chitietCauhinhDiems = new HashSet<ChitietCauhinhDiem>(0);

    public Diem() {
    }

    public Diem(Hocky hocky, HocsinhLophoc hocsinhLophoc, Monhoc monhoc) {
        this.hocky = hocky;
        this.hocsinhLophoc = hocsinhLophoc;
        this.monhoc = monhoc;
    }

    public Diem(Hocky hocky, HocsinhLophoc hocsinhLophoc, Monhoc monhoc, Double diem15Phut, Double diem1Tiet, Double diemCuoiKy, Set<ChitietCauhinhDiem> chitietCauhinhDiems) {
        this.hocky = hocky;
        this.hocsinhLophoc = hocsinhLophoc;
        this.monhoc = monhoc;
        this.diem15Phut = diem15Phut;
        this.diem1Tiet = diem1Tiet;
        this.diemCuoiKy = diemCuoiKy;
        this.chitietCauhinhDiems = chitietCauhinhDiems;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idDiem", unique = true, nullable = false)
    public Integer getIdDiem() {
        return this.idDiem;
    }

    public void setIdDiem(Integer idDiem) {
        this.idDiem = idDiem;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idHocKy", nullable = false)
    public Hocky getHocky() {
        return this.hocky;
    }

    public void setHocky(Hocky hocky) {
        this.hocky = hocky;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "idHocSinh", referencedColumnName = "idHocSinh", nullable = false),
        @JoinColumn(name = "idNamHoc", referencedColumnName = "idLopHoc", nullable = false),
        @JoinColumn(name = "idLop", referencedColumnName = "idNamHoc", nullable = false)})
    public HocsinhLophoc getHocsinhLophoc() {
        return this.hocsinhLophoc;
    }

    public void setHocsinhLophoc(HocsinhLophoc hocsinhLophoc) {
        this.hocsinhLophoc = hocsinhLophoc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMonHoc", nullable = false)
    public Monhoc getMonhoc() {
        return this.monhoc;
    }

    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }

    @Column(name = "15Phut", precision = 22, scale = 0)
    public Double getDiem15Phut() {
        return this.diem15Phut;
    }

    public void setDiem15Phut(Double diem15Phut) {
        this.diem15Phut = diem15Phut;
    }

    @Column(name = "1Tiet", precision = 22, scale = 0)
    public Double getDiem1Tiet() {
        return this.diem1Tiet;
    }

    public void setDiem1Tiet(Double diem1Tiet) {
        this.diem1Tiet = diem1Tiet;
    }

    @Column(name = "CuoiKy", precision = 22, scale = 0)
    public Double getDiemCuoiKy() {
        return this.diemCuoiKy;
    }

    public void setDiemCuoiKy(Double diemCuoiKy) {
        this.diemCuoiKy = diemCuoiKy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diem")
    public Set<ChitietCauhinhDiem> getChitietCauhinhDiems() {
        return this.chitietCauhinhDiems;
    }

    public void setChitietCauhinhDiems(Set<ChitietCauhinhDiem> chitietCauhinhDiems) {
        this.chitietCauhinhDiems = chitietCauhinhDiems;
    }

    @OneToMany
    public List<ChitietCauhinhDiem> getChitietCauhinhDieml() {
        return new ArrayList<>(this.chitietCauhinhDiems);
    }

    public void setChitietCauhinhDieml(List<ChitietCauhinhDiem> chitietCauhinhDieml) {
        this.chitietCauhinhDiems = new HashSet<>(chitietCauhinhDieml);
    }

    // so sanh theo Id
    public boolean equals(Diem obj) {
        return Objects.equals(obj.idDiem, this.idDiem);
    }

}
