package dto;
// Generated Apr 20, 2019 1:51:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HocsinhLophoc generated by hbm2java
 */
@Entity
@Table(name="hocsinh_lophoc"
    ,catalog="quanlyhocsinh"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"idHocSinh", "idNamHoc"}), @UniqueConstraint(columnNames="idHocSinhLopHoc")} 
)
public class HocsinhLophoc  implements java.io.Serializable {


     private HocsinhLophocId id;
     private Hocsinh hocsinh;
     private Lop lop;
     private Namhoc namhoc;
     private int idHocSinhLopHoc;
     private Set<Diem> diems = new HashSet<Diem>(0);

    public HocsinhLophoc() {
    }

	
    public HocsinhLophoc(HocsinhLophocId id, Hocsinh hocsinh, Lop lop, Namhoc namhoc, int idHocSinhLopHoc) {
        this.id = id;
        this.hocsinh = hocsinh;
        this.lop = lop;
        this.namhoc = namhoc;
        this.idHocSinhLopHoc = idHocSinhLopHoc;
    }
    public HocsinhLophoc(HocsinhLophocId id, Hocsinh hocsinh, Lop lop, Namhoc namhoc, int idHocSinhLopHoc, Set<Diem> diems) {
       this.id = id;
       this.hocsinh = hocsinh;
       this.lop = lop;
       this.namhoc = namhoc;
       this.idHocSinhLopHoc = idHocSinhLopHoc;
       this.diems = diems;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idHocSinh", column=@Column(name="idHocSinh", nullable=false) ), 
        @AttributeOverride(name="idLopHoc", column=@Column(name="idLopHoc", nullable=false) ), 
        @AttributeOverride(name="idNamHoc", column=@Column(name="idNamHoc", nullable=false) ) } )
    public HocsinhLophocId getId() {
        return this.id;
    }
    
    public void setId(HocsinhLophocId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHocSinh", nullable=false, insertable=false, updatable=false)
    public Hocsinh getHocsinh() {
        return this.hocsinh;
    }
    
    public void setHocsinh(Hocsinh hocsinh) {
        this.hocsinh = hocsinh;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLopHoc", nullable=false, insertable=false, updatable=false)
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idNamHoc", nullable=false, insertable=false, updatable=false)
    public Namhoc getNamhoc() {
        return this.namhoc;
    }
    
    public void setNamhoc(Namhoc namhoc) {
        this.namhoc = namhoc;
    }

    
    @Column(name="idHocSinhLopHoc", unique=true, nullable=false)
    public int getIdHocSinhLopHoc() {
        return this.idHocSinhLopHoc;
    }
    
    public void setIdHocSinhLopHoc(int idHocSinhLopHoc) {
        this.idHocSinhLopHoc = idHocSinhLopHoc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hocsinhLophoc")
    public Set<Diem> getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set<Diem> diems) {
        this.diems = diems;
    }




}


