package dto;
// Generated Apr 28, 2019 12:28:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Monhoc generated by hbm2java
 */
@Entity
@Table(name="monhoc"
    ,catalog="quanlyhocsinh"
)
public class Monhoc  implements java.io.Serializable {


     private Integer idMonHoc;
     private String tenMh;
     private boolean dangGiangDay;
     private Set<Diem> diems = new HashSet<Diem>(0);

    public Monhoc() {
    }

	
    public Monhoc(String tenMh, boolean dangGiangDay) {
        this.tenMh = tenMh;
        this.dangGiangDay = dangGiangDay;
    }
    public Monhoc(String tenMh, boolean dangGiangDay, Set<Diem> diems) {
       this.tenMh = tenMh;
       this.dangGiangDay = dangGiangDay;
       this.diems = diems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMonHoc", unique=true, nullable=false)
    public Integer getIdMonHoc() {
        return this.idMonHoc;
    }
    
    public void setIdMonHoc(Integer idMonHoc) {
        this.idMonHoc = idMonHoc;
    }

    
    @Column(name="TenMH", nullable=false, length=45)
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }

    
    @Column(name="dangGiangDay", nullable=false)
    public boolean isDangGiangDay() {
        return this.dangGiangDay;
    }
    
    public void setDangGiangDay(boolean dangGiangDay) {
        this.dangGiangDay = dangGiangDay;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="monhoc")
    public Set<Diem> getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set<Diem> diems) {
        this.diems = diems;
    }




}


