package dto;
// Generated May 24, 2019 9:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private Integer idMonHoc;
     private String tenMh;
     private int heSo;
     private boolean dangGiangDay;
     private Set<Diem> diems = new HashSet<Diem>(0);

    public Monhoc() {
    }

	
    public Monhoc(String tenMh, int heSo, boolean dangGiangDay) {
        this.tenMh = tenMh;
        this.heSo = heSo;
        this.dangGiangDay = dangGiangDay;
    }
    public Monhoc(String tenMh, int heSo, boolean dangGiangDay, Set<Diem> diems) {
       this.tenMh = tenMh;
       this.heSo = heSo;
       this.dangGiangDay = dangGiangDay;
       this.diems = diems;
    }
   
    public Integer getIdMonHoc() {
        return this.idMonHoc;
    }
    
    public void setIdMonHoc(Integer idMonHoc) {
        this.idMonHoc = idMonHoc;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public int getHeSo() {
        return this.heSo;
    }
    
    public void setHeSo(int heSo) {
        this.heSo = heSo;
    }
    public boolean isDangGiangDay() {
        return this.dangGiangDay;
    }
    
    public void setDangGiangDay(boolean dangGiangDay) {
        this.dangGiangDay = dangGiangDay;
    }
    public Set<Diem> getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set<Diem> diems) {
        this.diems = diems;
    }




}


