package hibernate;
// Generated Mar 22, 2019 9:31:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cauhinh generated by hbm2java
 */
public class Cauhinh  implements java.io.Serializable {


     private Integer idCauHinh;
     private String tenThuocTinh;
     private String loaiThuocTinh;
     private String giaTri;
     private String tenDayDu;
     private Set<ChitietCauhinhHocsinh> chitietCauhinhHocsinhs = new HashSet<ChitietCauhinhHocsinh>(0);
     private Set<ChitietCauhinhLop> chitietCauhinhLops = new HashSet<ChitietCauhinhLop>(0);
     private Set<ChitietCauhinhDiem> chitietCauhinhDiems = new HashSet<ChitietCauhinhDiem>(0);

    public Cauhinh() {
    }

	
    public Cauhinh(String tenThuocTinh, String loaiThuocTinh, String giaTri, String tenDayDu) {
        this.tenThuocTinh = tenThuocTinh;
        this.loaiThuocTinh = loaiThuocTinh;
        this.giaTri = giaTri;
        this.tenDayDu = tenDayDu;
    }
    public Cauhinh(String tenThuocTinh, String loaiThuocTinh, String giaTri, String tenDayDu, Set<ChitietCauhinhHocsinh> chitietCauhinhHocsinhs, Set<ChitietCauhinhLop> chitietCauhinhLops, Set<ChitietCauhinhDiem> chitietCauhinhDiems) {
       this.tenThuocTinh = tenThuocTinh;
       this.loaiThuocTinh = loaiThuocTinh;
       this.giaTri = giaTri;
       this.tenDayDu = tenDayDu;
       this.chitietCauhinhHocsinhs = chitietCauhinhHocsinhs;
       this.chitietCauhinhLops = chitietCauhinhLops;
       this.chitietCauhinhDiems = chitietCauhinhDiems;
    }
   
    public Integer getIdCauHinh() {
        return this.idCauHinh;
    }
    
    public void setIdCauHinh(Integer idCauHinh) {
        this.idCauHinh = idCauHinh;
    }
    public String getTenThuocTinh() {
        return this.tenThuocTinh;
    }
    
    public void setTenThuocTinh(String tenThuocTinh) {
        this.tenThuocTinh = tenThuocTinh;
    }
    public String getLoaiThuocTinh() {
        return this.loaiThuocTinh;
    }
    
    public void setLoaiThuocTinh(String loaiThuocTinh) {
        this.loaiThuocTinh = loaiThuocTinh;
    }
    public String getGiaTri() {
        return this.giaTri;
    }
    
    public void setGiaTri(String giaTri) {
        this.giaTri = giaTri;
    }
    public String getTenDayDu() {
        return this.tenDayDu;
    }
    
    public void setTenDayDu(String tenDayDu) {
        this.tenDayDu = tenDayDu;
    }
    public Set<ChitietCauhinhHocsinh> getChitietCauhinhHocsinhs() {
        return this.chitietCauhinhHocsinhs;
    }
    
    public void setChitietCauhinhHocsinhs(Set<ChitietCauhinhHocsinh> chitietCauhinhHocsinhs) {
        this.chitietCauhinhHocsinhs = chitietCauhinhHocsinhs;
    }
    public Set<ChitietCauhinhLop> getChitietCauhinhLops() {
        return this.chitietCauhinhLops;
    }
    
    public void setChitietCauhinhLops(Set<ChitietCauhinhLop> chitietCauhinhLops) {
        this.chitietCauhinhLops = chitietCauhinhLops;
    }
    public Set<ChitietCauhinhDiem> getChitietCauhinhDiems() {
        return this.chitietCauhinhDiems;
    }
    
    public void setChitietCauhinhDiems(Set<ChitietCauhinhDiem> chitietCauhinhDiems) {
        this.chitietCauhinhDiems = chitietCauhinhDiems;
    }




}


