package hibernate;
// Generated Mar 22, 2019 9:31:01 PM by Hibernate Tools 4.3.1



/**
 * ChitietCauhinhHocsinh generated by hbm2java
 */
public class ChitietCauhinhHocsinh  implements java.io.Serializable {


     private ChitietCauhinhHocsinhId id;
     private Cauhinh cauhinh;
     private Hocsinh hocsinh;
     private Boolean apDung;

    public ChitietCauhinhHocsinh() {
    }

	
    public ChitietCauhinhHocsinh(ChitietCauhinhHocsinhId id, Cauhinh cauhinh, Hocsinh hocsinh) {
        this.id = id;
        this.cauhinh = cauhinh;
        this.hocsinh = hocsinh;
    }
    public ChitietCauhinhHocsinh(ChitietCauhinhHocsinhId id, Cauhinh cauhinh, Hocsinh hocsinh, Boolean apDung) {
       this.id = id;
       this.cauhinh = cauhinh;
       this.hocsinh = hocsinh;
       this.apDung = apDung;
    }
   
    public ChitietCauhinhHocsinhId getId() {
        return this.id;
    }
    
    public void setId(ChitietCauhinhHocsinhId id) {
        this.id = id;
    }
    public Cauhinh getCauhinh() {
        return this.cauhinh;
    }
    
    public void setCauhinh(Cauhinh cauhinh) {
        this.cauhinh = cauhinh;
    }
    public Hocsinh getHocsinh() {
        return this.hocsinh;
    }
    
    public void setHocsinh(Hocsinh hocsinh) {
        this.hocsinh = hocsinh;
    }
    public Boolean getApDung() {
        return this.apDung;
    }
    
    public void setApDung(Boolean apDung) {
        this.apDung = apDung;
    }




}


