package hibernate;
// Generated Mar 22, 2019 9:31:01 PM by Hibernate Tools 4.3.1



/**
 * ChitietCauhinhHocsinhId generated by hbm2java
 */
public class ChitietCauhinhHocsinhId  implements java.io.Serializable {


     private int idHocSinh;
     private int idCauHinh;

    public ChitietCauhinhHocsinhId() {
    }

    public ChitietCauhinhHocsinhId(int idHocSinh, int idCauHinh) {
       this.idHocSinh = idHocSinh;
       this.idCauHinh = idCauHinh;
    }
   
    public int getIdHocSinh() {
        return this.idHocSinh;
    }
    
    public void setIdHocSinh(int idHocSinh) {
        this.idHocSinh = idHocSinh;
    }
    public int getIdCauHinh() {
        return this.idCauHinh;
    }
    
    public void setIdCauHinh(int idCauHinh) {
        this.idCauHinh = idCauHinh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitietCauhinhHocsinhId) ) return false;
		 ChitietCauhinhHocsinhId castOther = ( ChitietCauhinhHocsinhId ) other; 
         
		 return (this.getIdHocSinh()==castOther.getIdHocSinh())
 && (this.getIdCauHinh()==castOther.getIdCauHinh());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHocSinh();
         result = 37 * result + this.getIdCauHinh();
         return result;
   }   


}


