package hibernate;
// Generated Mar 22, 2019 9:31:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private Integer idDiem;
     private Hocky hocky;
     private Monhoc monhoc;
     private Double diem15phut;
     private Double diem1tiet;
     private Double cuoiKy;
     private int idHocSinh;
     private int idNamHoc;
     private Set<ChitietCauhinhDiem> chitietCauhinhDiems = new HashSet<ChitietCauhinhDiem>(0);

    public Diem() {
    }

	
    public Diem(Hocky hocky, Monhoc monhoc, int idHocSinh, int idNamHoc) {
        this.hocky = hocky;
        this.monhoc = monhoc;
        this.idHocSinh = idHocSinh;
        this.idNamHoc = idNamHoc;
    }
    public Diem(Hocky hocky, Monhoc monhoc, Double diem15phut, Double diem1tiet, Double cuoiKy, int idHocSinh, int idNamHoc, Set<ChitietCauhinhDiem> chitietCauhinhDiems) {
       this.hocky = hocky;
       this.monhoc = monhoc;
       this.diem15phut = diem15phut;
       this.diem1tiet = diem1tiet;
       this.cuoiKy = cuoiKy;
       this.idHocSinh = idHocSinh;
       this.idNamHoc = idNamHoc;
       this.chitietCauhinhDiems = chitietCauhinhDiems;
    }
   
    public Integer getIdDiem() {
        return this.idDiem;
    }
    
    public void setIdDiem(Integer idDiem) {
        this.idDiem = idDiem;
    }
    public Hocky getHocky() {
        return this.hocky;
    }
    
    public void setHocky(Hocky hocky) {
        this.hocky = hocky;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public Double getdiem15phut() {
        return this.diem15phut;
    }
    
    public void setdiem15phut(Double diem15phut) {
        this.diem15phut = diem15phut;
    }
    public Double getdiem1tiet() {
        return this.diem1tiet;
    }
    
    public void setdiem1tiet(Double diem1tiet) {
        this.diem1tiet = diem1tiet;
    }
    public Double getCuoiKy() {
        return this.cuoiKy;
    }
    
    public void setCuoiKy(Double cuoiKy) {
        this.cuoiKy = cuoiKy;
    }
    public int getIdHocSinh() {
        return this.idHocSinh;
    }
    
    public void setIdHocSinh(int idHocSinh) {
        this.idHocSinh = idHocSinh;
    }
    public int getIdNamHoc() {
        return this.idNamHoc;
    }
    
    public void setIdNamHoc(int idNamHoc) {
        this.idNamHoc = idNamHoc;
    }
    public Set<ChitietCauhinhDiem> getChitietCauhinhDiems() {
        return this.chitietCauhinhDiems;
    }
    
    public void setChitietCauhinhDiems(Set<ChitietCauhinhDiem> chitietCauhinhDiems) {
        this.chitietCauhinhDiems = chitietCauhinhDiems;
    }




}


