package hibernate;
// Generated Mar 22, 2019 9:31:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lop generated by hbm2java
 */
public class Lop  implements java.io.Serializable {


     private Integer idLop;
     private String tenLop;
     private int khoi;
     private byte tinhTrang;
     private Set<ChitietCauhinhLop> chitietCauhinhLops = new HashSet<ChitietCauhinhLop>(0);

    public Lop() {
    }

	
    public Lop(String tenLop, int khoi, byte tinhTrang) {
        this.tenLop = tenLop;
        this.khoi = khoi;
        this.tinhTrang = tinhTrang;
    }
    public Lop(String tenLop, int khoi, byte tinhTrang, Set<ChitietCauhinhLop> chitietCauhinhLops) {
       this.tenLop = tenLop;
       this.khoi = khoi;
       this.tinhTrang = tinhTrang;
       this.chitietCauhinhLops = chitietCauhinhLops;
    }
   
    public Integer getIdLop() {
        return this.idLop;
    }
    
    public void setIdLop(Integer idLop) {
        this.idLop = idLop;
    }
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }
    public int getKhoi() {
        return this.khoi;
    }
    
    public void setKhoi(int khoi) {
        this.khoi = khoi;
    }
    public byte getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(byte tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set<ChitietCauhinhLop> getChitietCauhinhLops() {
        return this.chitietCauhinhLops;
    }
    
    public void setChitietCauhinhLops(Set<ChitietCauhinhLop> chitietCauhinhLops) {
        this.chitietCauhinhLops = chitietCauhinhLops;
    }




}


