package hibernate;
// Generated Mar 22, 2019 9:31:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Namhoc generated by hbm2java
 */
public class Namhoc  implements java.io.Serializable {


     private Integer idNamHoc;
     private String tenNamHoc;
     private Set<ChitietCauhinhLop> chitietCauhinhLops = new HashSet<ChitietCauhinhLop>(0);

    public Namhoc() {
    }

	
    public Namhoc(String tenNamHoc) {
        this.tenNamHoc = tenNamHoc;
    }
    public Namhoc(String tenNamHoc, Set<ChitietCauhinhLop> chitietCauhinhLops) {
       this.tenNamHoc = tenNamHoc;
       this.chitietCauhinhLops = chitietCauhinhLops;
    }
   
    public Integer getIdNamHoc() {
        return this.idNamHoc;
    }
    
    public void setIdNamHoc(Integer idNamHoc) {
        this.idNamHoc = idNamHoc;
    }
    public String getTenNamHoc() {
        return this.tenNamHoc;
    }
    
    public void setTenNamHoc(String tenNamHoc) {
        this.tenNamHoc = tenNamHoc;
    }
    public Set<ChitietCauhinhLop> getChitietCauhinhLops() {
        return this.chitietCauhinhLops;
    }
    
    public void setChitietCauhinhLops(Set<ChitietCauhinhLop> chitietCauhinhLops) {
        this.chitietCauhinhLops = chitietCauhinhLops;
    }




}


