/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dal.CauHinhDAL;
import dto.Cauhinh;
import dto.Nguoidung;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuhuy
 */
public class ConfigMeJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfigMeJInternalFrame
     */
    public ConfigMeJInternalFrame() {
        initComponents();
        LoadData();
    }

    dto.Nguoidung nd;

    public ConfigMeJInternalFrame(Nguoidung nguoidung) {
        initComponents();
        nd = nguoidung;
        lblTenTaiKhoan.setText(nd.getHoTen());
        LoadData();
    }

    private void LoadData() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID cấu hình");
        dtm.addColumn("Tên đầy đủ");
        dtm.addColumn("Giá trị");

        for (Cauhinh a : new CauHinhDAL().getAll()) {
            dtm.addRow(new Object[]{a.getIdCauHinh(), a.getTenDayDu(), a.getGiaTri()});
        }

        this.jTableCauHinh.setModel(dtm);
        this.jTableCauHinh.getColumnModel().getColumn(0).setPreferredWidth(80);  //ID cấu hình
        this.jTableCauHinh.getColumnModel().getColumn(1).setPreferredWidth(150); //Tên đầy đủ
        this.jTableCauHinh.getColumnModel().getColumn(2).setPreferredWidth(120); //Giá trị
        this.jTableCauHinh.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCauHinh = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDayDu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIdCauHinh = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();

        setClosable(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý cấu hình");

        lblTenTaiKhoan.setText("Tên tài khoản");

        jTableCauHinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCauHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCauHinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCauHinh);

        jLabel1.setText("Tên đầy đủ:");

        txtTenDayDu.setEditable(false);

        jLabel2.setText("Giá trị (*):");

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jLabel4.setText("Id cấu hình:");

        txtIdCauHinh.setEditable(false);

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenDayDu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdCauHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuayLai)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdCauHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDayDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnQuayLai))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTenTaiKhoan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCauHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCauHinhMouseClicked
        // TODO add your handling code here:
        int id = Integer.parseInt(this.jTableCauHinh.getValueAt(this.jTableCauHinh.getSelectedRow(), 0).toString());
        Cauhinh a = new CauHinhDAL().getById(id);

        this.txtIdCauHinh.setText(a.getIdCauHinh().toString());
        this.txtTenDayDu.setText(a.getTenDayDu());
        this.txtGiaTri.setText(a.getGiaTri());
    }//GEN-LAST:event_jTableCauHinhMouseClicked

    public void UpdateConfig(Cauhinh a) {
        if (new CauHinhDAL().update(a)) {
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            LoadData();
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        int idCauHinh = Integer.parseInt(txtIdCauHinh.getText());
        String giaTri = txtGiaTri.getText();
        Cauhinh b = new CauHinhDAL().getById(idCauHinh);

        Cauhinh a = new Cauhinh();
        a.setIdCauHinh(idCauHinh);
        a.setTenThuocTinh(b.getTenThuocTinh());
        a.setLoaiThuocTinh(b.getLoaiThuocTinh());
        a.setGiaTri(giaTri);
        a.setTenDayDu(b.getTenDayDu());

        Cauhinh cauHinhToiThieu = new CauHinhDAL().getByName("TuoiToiThieu");
        Cauhinh cauHinhToiDa = new CauHinhDAL().getByName("TuoiToiDa");

        if (giaTri.equals("")) {
            JOptionPane.showMessageDialog(null, "Giá trị không được để trống");
        } else if (b.getTenThuocTinh().equals("DiemChuanDatMon")) {
            try {
                Double giatri = Double.parseDouble(giaTri);
                if (giatri <= 0) {
                    JOptionPane.showMessageDialog(null, "Điểm chuẩn đạt môn là số thập phân hoặc số nguyên > 0");
                } else {
                    UpdateConfig(a);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm chuẩn đạt môn là số thập phân hoặc số nguyên > 0");
            }
        } else {
            try {
                int giatri = Integer.parseInt(giaTri);
                if (giatri <= 0) {
                    JOptionPane.showMessageDialog(null, "Giá trị phải là số nguyên > 0");
                } else if (b.getTenThuocTinh().equals("TuoiToiThieu")) {
                    if (giatri >= Integer.parseInt(cauHinhToiDa.getGiaTri())) {
                        JOptionPane.showMessageDialog(null, "Tuổi tối thiểu phải <= tuổi tối đa");
                    } else {
                        UpdateConfig(a);
                    }
                } else if (b.getTenThuocTinh().equals("TuoiToiDa")) {
                    if (giatri <= Integer.parseInt(cauHinhToiThieu.getGiaTri())) {
                        JOptionPane.showMessageDialog(null, "Tuổi tối đa phải >= tuổi tối thiểu");
                    } else {
                        UpdateConfig(a);
                    }
                } else {
                    UpdateConfig(a);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Giá trị phải là số nguyên > 0");
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        ManageMainJFrame f = new ManageMainJFrame(nd);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCauHinh;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtIdCauHinh;
    private javax.swing.JTextField txtTenDayDu;
    // End of variables declaration//GEN-END:variables
}
