package gui;

import bll.HocsinhLopHocBLL;
import dal.HocsinhDAL;
import dal.HocsinhLophocDAL;
import dal.LopDAL;
import dal.NamhocDAL;
import dto.Hocsinh;
import dto.HocsinhLophoc;
import dto.Lop;
import dto.Namhoc;
import dto.Nguoidung;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuhuy
 */
public class ShowListClassJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShowClassList
     */
    public ShowListClassJFrame() {
        initComponents();
        LoadCbo();
    }

    dto.Nguoidung nd;

    public ShowListClassJFrame(Nguoidung nguoidung) {
        initComponents();
        nd = nguoidung;
        lblTenTaiKhoan.setText(nd.getHoTen());
        LoadCbo();
    }

    public void LoadCbo() {

        for (Lop a : new LopDAL().getAll()) {
            cboTenLop.addItem(a.getTenLop());
        }

        for (Namhoc a : new NamhocDAL().getAll()) {
            cboNamHoc.addItem(a.getTenNamHoc());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachLop = new javax.swing.JTable();
        lblTenTaiKhoan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cboNamHoc = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        btnXem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboTenLop = new javax.swing.JComboBox<String>();
        txtTenLop = new javax.swing.JTextField();
        txtSiSo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách lơp");
        setPreferredSize(new java.awt.Dimension(900, 440));

        jLabel2.setText("Tên lớp:");

        jLabel4.setText("Sỉ số:");

        jTableDanhSachLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MSHS", "Họ tên", "Giới tính", "Năm sinh", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(jTableDanhSachLop);

        lblTenTaiKhoan.setText("Tên tài khoản");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Năm học:");

        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên lớp:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXem)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnXem)
                    .addComponent(jLabel1)
                    .addComponent(cboTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtTenLop.setEditable(false);

        txtSiSo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblTenTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtSiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 310, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSiSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed

        String tenLop = this.cboTenLop.getSelectedItem().toString();
        Lop lop = new LopDAL().getByTen(tenLop);

        String tenNamHoc = this.cboNamHoc.getSelectedItem().toString();
        Namhoc namhoc = new NamhocDAL().getByTen(tenNamHoc);

        List<HocsinhLophoc> dsHocsinhLopHoc = new HocsinhLophocDAL().getByNamHocLop(namhoc, lop);
        int SiSoLop = dsHocsinhLopHoc.size();

        if (SiSoLop == 0) {
            JOptionPane.showMessageDialog(null, "Năm học " + tenNamHoc + " không có lớp " + tenLop);
        } else {
            txtTenLop.setText(tenLop);
            txtSiSo.setText(Integer.toString(SiSoLop));
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("STT");
            dtm.addColumn("MSHS");
            dtm.addColumn("Họ tên");
            dtm.addColumn("Giới tính");
            dtm.addColumn("Năm sinh");
            dtm.addColumn("Địa chỉ");
            int i = 0, stt = 1;

            for (HocsinhLophoc a : dsHocsinhLopHoc) {
                if (i < SiSoLop) {
                    int id = dsHocsinhLopHoc.get(i).getHocsinh().getIdHocSinh();
                    Hocsinh hs = new HocsinhDAL().getById(id);
                    int year = Integer.parseInt(hs.getNgaySinh().substring(6));
                    
                    dtm.addRow(new Object[]{stt, hs.getIdHocSinh(), hs.getHoTen(), hs.getGioiTinh(),
                        year, hs.getDiaChi()});
                    i++;
                    stt++;
                }
            }

            this.jTableDanhSachLop.setModel(dtm);

            this.jTableDanhSachLop.getColumnModel().getColumn(0).setPreferredWidth(10);  //STT
            this.jTableDanhSachLop.getColumnModel().getColumn(1).setPreferredWidth(10); //MSHS
            this.jTableDanhSachLop.getColumnModel().getColumn(2).setPreferredWidth(120); //Họ tên
            this.jTableDanhSachLop.getColumnModel().getColumn(3).setPreferredWidth(20); //Giới tính
            this.jTableDanhSachLop.getColumnModel().getColumn(4).setPreferredWidth(20);  //Ngày sinh
            this.jTableDanhSachLop.getColumnModel().getColumn(5).setPreferredWidth(200); //Địa chỉ

            this.jTableDanhSachLop.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        }

    }//GEN-LAST:event_btnXemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowListClassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowListClassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowListClassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowListClassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowListClassJFrame f = new ShowListClassJFrame();
                f.setLocationRelativeTo(null);
                f.setVisible(true);
                f.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXem;
    private javax.swing.JComboBox<String> cboNamHoc;
    private javax.swing.JComboBox<String> cboTenLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDanhSachLop;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JTextField txtSiSo;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
