-- MySQL Script generated by MySQL Workbench
-- Sat Mar  9 19:31:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QLHS
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `QLHS` ;

-- -----------------------------------------------------
-- Schema QLHS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QLHS` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
USE `QLHS` ;

-- -----------------------------------------------------
-- Table `QLHS`.`Lop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`Lop` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`Lop` (
  `idLop` INT NOT NULL AUTO_INCREMENT,
  `TenLop` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `SiSo` INT NOT NULL,
  `Khoi` INT NOT NULL,
  PRIMARY KEY (`idLop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`HocSinh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`HocSinh` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`HocSinh` (
  `idHocSinh` INT NOT NULL AUTO_INCREMENT,
  `HoTen` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `NgaySinh` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `GioiTinh` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `DiaChi` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `idLop` INT NOT NULL,
  PRIMARY KEY (`idHocSinh`),
  INDEX `fk_HocSinh_Lop1_idx` (`idLop` ASC),
  CONSTRAINT `fk_HocSinh_Lop1`
    FOREIGN KEY (`idLop`)
    REFERENCES `QLHS`.`Lop` (`idLop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`MonHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`MonHoc` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`MonHoc` (
  `idMonHoc` INT NOT NULL AUTO_INCREMENT,
  `TenMH` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idMonHoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`HocKy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`HocKy` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`HocKy` (
  `idHocKy` INT NOT NULL AUTO_INCREMENT,
  `TenHocKy` INT NOT NULL,
  PRIMARY KEY (`idHocKy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`Diem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`Diem` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`Diem` (
  `idDiem` INT NOT NULL AUTO_INCREMENT,
  `15Phut` DOUBLE NULL DEFAULT NULL,
  `1Tiet` DOUBLE NULL DEFAULT NULL,
  `CuoiKy` DOUBLE NULL DEFAULT NULL,
  `DTB` DOUBLE NULL DEFAULT NULL,
  `idHocSinh` INT NOT NULL,
  `idMonHoc` INT NOT NULL,
  `idHocKy` INT NOT NULL,
  PRIMARY KEY (`idDiem`),
  INDEX `fk_Diem_HocSinh1_idx` (`idHocSinh` ASC),
  INDEX `fk_Diem_MonHoc1_idx` (`idMonHoc` ASC),
  INDEX `fk_Diem_HocKy1_idx` (`idHocKy` ASC),
  CONSTRAINT `fk_Diem_HocSinh1`
    FOREIGN KEY (`idHocSinh`)
    REFERENCES `QLHS`.`HocSinh` (`idHocSinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diem_MonHoc1`
    FOREIGN KEY (`idMonHoc`)
    REFERENCES `QLHS`.`MonHoc` (`idMonHoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diem_HocKy1`
    FOREIGN KEY (`idHocKy`)
    REFERENCES `QLHS`.`HocKy` (`idHocKy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `QLHS`.`CauHinh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`CauHinh` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`CauHinh` (
  `idCauHinh` INT NOT NULL AUTO_INCREMENT,
  `TenThuocTinh` VARCHAR(45) NOT NULL,
  `LoaiThuocTinh` VARCHAR(45) NOT NULL,
  `GiaTri` VARCHAR(45) NOT NULL,
  `TenDayDu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCauHinh`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`ChiTiet_CauHinh_HocSinh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`ChiTiet_CauHinh_HocSinh` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`ChiTiet_CauHinh_HocSinh` (
  `idHocSinh` INT NOT NULL,
  `idCauHinh` INT NOT NULL,
  PRIMARY KEY (`idHocSinh`, `idCauHinh`),
  INDEX `fk_HocSinh_has_CauHinh_CauHinh1_idx` (`idCauHinh` ASC),
  INDEX `fk_HocSinh_has_CauHinh_HocSinh1_idx` (`idHocSinh` ASC),
  CONSTRAINT `fk_HocSinh_has_CauHinh_HocSinh1`
    FOREIGN KEY (`idHocSinh`)
    REFERENCES `QLHS`.`HocSinh` (`idHocSinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HocSinh_has_CauHinh_CauHinh1`
    FOREIGN KEY (`idCauHinh`)
    REFERENCES `QLHS`.`CauHinh` (`idCauHinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`ChiTiet_CauHinh_Lop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`ChiTiet_CauHinh_Lop` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`ChiTiet_CauHinh_Lop` (
  `idLop` INT NOT NULL,
  `idCauHinh` INT NOT NULL,
  PRIMARY KEY (`idLop`, `idCauHinh`),
  INDEX `fk_Lop_has_CauHinh_CauHinh1_idx` (`idCauHinh` ASC),
  INDEX `fk_Lop_has_CauHinh_Lop1_idx` (`idLop` ASC),
  CONSTRAINT `fk_Lop_has_CauHinh_Lop1`
    FOREIGN KEY (`idLop`)
    REFERENCES `QLHS`.`Lop` (`idLop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lop_has_CauHinh_CauHinh1`
    FOREIGN KEY (`idCauHinh`)
    REFERENCES `QLHS`.`CauHinh` (`idCauHinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QLHS`.`ChiTiet_CauHinh_Diem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QLHS`.`ChiTiet_CauHinh_Diem` ;

CREATE TABLE IF NOT EXISTS `QLHS`.`ChiTiet_CauHinh_Diem` (
  `idDiem` INT NOT NULL,
  `idCauHinh` INT NOT NULL,
  PRIMARY KEY (`idDiem`, `idCauHinh`),
  INDEX `fk_Diem_has_CauHinh_CauHinh1_idx` (`idCauHinh` ASC),
  INDEX `fk_Diem_has_CauHinh_Diem1_idx` (`idDiem` ASC),
  CONSTRAINT `fk_Diem_has_CauHinh_Diem1`
    FOREIGN KEY (`idDiem`)
    REFERENCES `QLHS`.`Diem` (`idDiem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diem_has_CauHinh_CauHinh1`
    FOREIGN KEY (`idCauHinh`)
    REFERENCES `QLHS`.`CauHinh` (`idCauHinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
