package com.dto;
// Generated Mar 24, 2019 2:56:57 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Monhoc generated by hbm2java
 */
@Entity
@Table(name="monhoc"
    ,catalog="quanlyhocsinh"
)
public class Monhoc  implements java.io.Serializable {


     private Integer idMonHoc;
     private String tenMh;
     private Set<Diem> diems = new HashSet<Diem>(0);

    public Monhoc() {
    }

	
    public Monhoc(String tenMh) {
        this.tenMh = tenMh;
    }
    public Monhoc(String tenMh, Set<Diem> diems) {
       this.tenMh = tenMh;
       this.diems = diems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMonHoc", unique=true, nullable=false)
    public Integer getIdMonHoc() {
        return this.idMonHoc;
    }
    
    public void setIdMonHoc(Integer idMonHoc) {
        this.idMonHoc = idMonHoc;
    }

    
    @Column(name="TenMH", nullable=false, length=45)
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="monhoc")
    public Set<Diem> getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set<Diem> diems) {
        this.diems = diems;
    }

@OneToMany
    public List<Diem> getDieml() {
        return new ArrayList<Diem>(this.diems);
    }
    
    public void setDieml(List<Diem> dieml) {
        this.diems =new HashSet<Diem>(dieml);
    }


}


