package hirbenate;
// Generated Mar 20, 2019 5:24:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Cauhinh generated by hbm2java
 */
@Entity
@Table(name="cauhinh"
    ,catalog="quanlyhocsinh"
)
public class Cauhinh  implements java.io.Serializable {


     private Integer idCauHinh;
     private String tenThuocTinh;
     private String loaiThuocTinh;
     private String giaTri;
     private String tenDayDu;
     private Set<Hocsinh> hocsinhs = new HashSet<Hocsinh>(0);
     private Set<Lop> lops = new HashSet<Lop>(0);
     private Set<Diem> diems = new HashSet<Diem>(0);

    public Cauhinh() {
    }

	
    public Cauhinh(String tenThuocTinh, String loaiThuocTinh, String giaTri, String tenDayDu) {
        this.tenThuocTinh = tenThuocTinh;
        this.loaiThuocTinh = loaiThuocTinh;
        this.giaTri = giaTri;
        this.tenDayDu = tenDayDu;
    }
    public Cauhinh(String tenThuocTinh, String loaiThuocTinh, String giaTri, String tenDayDu, Set<Hocsinh> hocsinhs, Set<Lop> lops, Set<Diem> diems) {
       this.tenThuocTinh = tenThuocTinh;
       this.loaiThuocTinh = loaiThuocTinh;
       this.giaTri = giaTri;
       this.tenDayDu = tenDayDu;
       this.hocsinhs = hocsinhs;
       this.lops = lops;
       this.diems = diems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCauHinh", unique=true, nullable=false)
    public Integer getIdCauHinh() {
        return this.idCauHinh;
    }
    
    public void setIdCauHinh(Integer idCauHinh) {
        this.idCauHinh = idCauHinh;
    }

    
    @Column(name="TenThuocTinh", nullable=false, length=45)
    public String getTenThuocTinh() {
        return this.tenThuocTinh;
    }
    
    public void setTenThuocTinh(String tenThuocTinh) {
        this.tenThuocTinh = tenThuocTinh;
    }

    
    @Column(name="LoaiThuocTinh", nullable=false, length=45)
    public String getLoaiThuocTinh() {
        return this.loaiThuocTinh;
    }
    
    public void setLoaiThuocTinh(String loaiThuocTinh) {
        this.loaiThuocTinh = loaiThuocTinh;
    }

    
    @Column(name="GiaTri", nullable=false, length=45)
    public String getGiaTri() {
        return this.giaTri;
    }
    
    public void setGiaTri(String giaTri) {
        this.giaTri = giaTri;
    }

    
    @Column(name="TenDayDu", nullable=false, length=45)
    public String getTenDayDu() {
        return this.tenDayDu;
    }
    
    public void setTenDayDu(String tenDayDu) {
        this.tenDayDu = tenDayDu;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="cauhinhs")
    public Set<Hocsinh> getHocsinhs() {
        return this.hocsinhs;
    }
    
    public void setHocsinhs(Set<Hocsinh> hocsinhs) {
        this.hocsinhs = hocsinhs;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="cauhinhs")
    public Set<Lop> getLops() {
        return this.lops;
    }
    
    public void setLops(Set<Lop> lops) {
        this.lops = lops;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="cauhinhs")
    public Set<Diem> getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set<Diem> diems) {
        this.diems = diems;
    }




}


