package hirbenate;
// Generated Mar 20, 2019 5:24:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Diem generated by hbm2java
 */
@Entity
@Table(name="diem"
    ,catalog="quanlyhocsinh"
)
public class Diem  implements java.io.Serializable {


     private Integer idDiem;
     private Hocky hocky;
     private Hocsinh hocsinh;
     private Monhoc monhoc;
     private Double diem15phut;
     private Double diem1tiet;
     private Double cuoiKy;
     private Double dtb;
     private Set<Cauhinh> cauhinhs = new HashSet<Cauhinh>(0);

    public Diem() {
    }

	
    public Diem(Hocky hocky, Hocsinh hocsinh, Monhoc monhoc) {
        this.hocky = hocky;
        this.hocsinh = hocsinh;
        this.monhoc = monhoc;
    }
    public Diem(Hocky hocky, Hocsinh hocsinh, Monhoc monhoc, Double diem15phut, Double diem1tiet, Double cuoiKy, Double dtb, Set<Cauhinh> cauhinhs) {
       this.hocky = hocky;
       this.hocsinh = hocsinh;
       this.monhoc = monhoc;
       this.diem15phut = diem15phut;
       this.diem1tiet = diem1tiet;
       this.cuoiKy = cuoiKy;
       this.dtb = dtb;
       this.cauhinhs = cauhinhs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDiem", unique=true, nullable=false)
    public Integer getIdDiem() {
        return this.idDiem;
    }
    
    public void setIdDiem(Integer idDiem) {
        this.idDiem = idDiem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHocKy", nullable=false)
    public Hocky getHocky() {
        return this.hocky;
    }
    
    public void setHocky(Hocky hocky) {
        this.hocky = hocky;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHocSinh", nullable=false)
    public Hocsinh getHocsinh() {
        return this.hocsinh;
    }
    
    public void setHocsinh(Hocsinh hocsinh) {
        this.hocsinh = hocsinh;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMonHoc", nullable=false)
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }

    
    @Column(name="15Phut", precision=22, scale=0)
    public Double getdiem15phut() {
        return this.diem15phut;
    }
    
    public void setdiem15phut(Double diem15phut) {
        this.diem15phut = diem15phut;
    }

    
    @Column(name="1Tiet", precision=22, scale=0)
    public Double getdiem1tiet() {
        return this.diem1tiet;
    }
    
    public void setdiem1tiet(Double diem1tiet) {
        this.diem1tiet = diem1tiet;
    }

    
    @Column(name="CuoiKy", precision=22, scale=0)
    public Double getCuoiKy() {
        return this.cuoiKy;
    }
    
    public void setCuoiKy(Double cuoiKy) {
        this.cuoiKy = cuoiKy;
    }

    
    @Column(name="DTB", precision=22, scale=0)
    public Double getDtb() {
        return this.dtb;
    }
    
    public void setDtb(Double dtb) {
        this.dtb = dtb;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="chitiet_cauhinh_diem", catalog="quanlyhocsinh", joinColumns = { 
        @JoinColumn(name="idDiem", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idCauHinh", nullable=false, updatable=false) })
    public Set<Cauhinh> getCauhinhs() {
        return this.cauhinhs;
    }
    
    public void setCauhinhs(Set<Cauhinh> cauhinhs) {
        this.cauhinhs = cauhinhs;
    }




}


