package hirbenate;
// Generated Mar 20, 2019 5:24:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hocsinh generated by hbm2java
 */
@Entity
@Table(name="hocsinh"
    ,catalog="quanlyhocsinh"
)
public class Hocsinh  implements java.io.Serializable {


     private Integer idHocSinh;
     private Lop lop;
     private String hoTen;
     private Date ngaySinh;
     private String email;
     private String gioiTinh;
     private String diaChi;
     private byte tinhTrang;
     private Set<Diem> diems = new HashSet<Diem>(0);
     private Set<Cauhinh> cauhinhs = new HashSet<Cauhinh>(0);

    public Hocsinh() {
    }

	
    public Hocsinh(Lop lop, String hoTen, Date ngaySinh, String email, String gioiTinh, String diaChi, byte tinhTrang) {
        this.lop = lop;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.email = email;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.tinhTrang = tinhTrang;
    }
    public Hocsinh(Lop lop, String hoTen, Date ngaySinh, String email, String gioiTinh, String diaChi, byte tinhTrang, Set<Diem> diems, Set<Cauhinh> cauhinhs) {
       this.lop = lop;
       this.hoTen = hoTen;
       this.ngaySinh = ngaySinh;
       this.email = email;
       this.gioiTinh = gioiTinh;
       this.diaChi = diaChi;
       this.tinhTrang = tinhTrang;
       this.diems = diems;
       this.cauhinhs = cauhinhs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHocSinh", unique=true, nullable=false)
    public Integer getIdHocSinh() {
        return this.idHocSinh;
    }
    
    public void setIdHocSinh(Integer idHocSinh) {
        this.idHocSinh = idHocSinh;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLop", nullable=false)
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }

    
    @Column(name="HoTen", nullable=false, length=45)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgaySinh", nullable=false, length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="Email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="GioiTinh", nullable=false, length=45)
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    
    @Column(name="DiaChi", nullable=false, length=200)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="TinhTrang", nullable=false)
    public byte getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(byte tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hocsinh")
    public Set<Diem> getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set<Diem> diems) {
        this.diems = diems;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="chitiet_cauhinh_hocsinh", catalog="quanlyhocsinh", joinColumns = { 
        @JoinColumn(name="idHocSinh", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idCauHinh", nullable=false, updatable=false) })
    public Set<Cauhinh> getCauhinhs() {
        return this.cauhinhs;
    }
    
    public void setCauhinhs(Set<Cauhinh> cauhinhs) {
        this.cauhinhs = cauhinhs;
    }




}


