package hirbenate;
// Generated Mar 20, 2019 5:24:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lop generated by hbm2java
 */
@Entity
@Table(name="lop"
    ,catalog="quanlyhocsinh"
)
public class Lop  implements java.io.Serializable {


     private Integer idLop;
     private String tenLop;
     private int siSo;
     private int khoi;
     private String namHoc;
     private byte tinhTrang;
     private Set<Hocsinh> hocsinhs = new HashSet<Hocsinh>(0);
     private Set<Cauhinh> cauhinhs = new HashSet<Cauhinh>(0);

    public Lop() {
    }

	
    public Lop(String tenLop, int siSo, int khoi, String namHoc, byte tinhTrang) {
        this.tenLop = tenLop;
        this.siSo = siSo;
        this.khoi = khoi;
        this.namHoc = namHoc;
        this.tinhTrang = tinhTrang;
    }
    public Lop(String tenLop, int siSo, int khoi, String namHoc, byte tinhTrang, Set<Hocsinh> hocsinhs, Set<Cauhinh> cauhinhs) {
       this.tenLop = tenLop;
       this.siSo = siSo;
       this.khoi = khoi;
       this.namHoc = namHoc;
       this.tinhTrang = tinhTrang;
       this.hocsinhs = hocsinhs;
       this.cauhinhs = cauhinhs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idLop", unique=true, nullable=false)
    public Integer getIdLop() {
        return this.idLop;
    }
    
    public void setIdLop(Integer idLop) {
        this.idLop = idLop;
    }

    
    @Column(name="TenLop", nullable=false, length=45)
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }

    
    @Column(name="SiSo", nullable=false)
    public int getSiSo() {
        return this.siSo;
    }
    
    public void setSiSo(int siSo) {
        this.siSo = siSo;
    }

    
    @Column(name="Khoi", nullable=false)
    public int getKhoi() {
        return this.khoi;
    }
    
    public void setKhoi(int khoi) {
        this.khoi = khoi;
    }

    
    @Column(name="NamHoc", nullable=false, length=45)
    public String getNamHoc() {
        return this.namHoc;
    }
    
    public void setNamHoc(String namHoc) {
        this.namHoc = namHoc;
    }

    
    @Column(name="TinhTrang", nullable=false)
    public byte getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(byte tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lop")
    public Set<Hocsinh> getHocsinhs() {
        return this.hocsinhs;
    }
    
    public void setHocsinhs(Set<Hocsinh> hocsinhs) {
        this.hocsinhs = hocsinhs;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="chitiet_cauhinh_lop", catalog="quanlyhocsinh", joinColumns = { 
        @JoinColumn(name="idLop", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idCauHinh", nullable=false, updatable=false) })
    public Set<Cauhinh> getCauhinhs() {
        return this.cauhinhs;
    }
    
    public void setCauhinhs(Set<Cauhinh> cauhinhs) {
        this.cauhinhs = cauhinhs;
    }




}


